/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dmx_dmxConnect */

#ifndef _Included_dmx_dmxConnect
#define _Included_dmx_dmxConnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dmx_dmxConnect
 * Method:    open
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    isSimulation
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_dmx_dmxConnect_isSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    stopFade
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_stopFade
  (JNIEnv *, jobject, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    setStartCode
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setStartCode
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     dmx_dmxConnect
 * Method:    setProfile
 * Signature: (II[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setProfile
  (JNIEnv *, jobject, jint, jint, jshortArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    setProfiles
 * Signature: (I[[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setProfiles
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    clearProfile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_clearProfile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    clearProfiles
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_clearProfiles
  (JNIEnv *, jobject, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    setProportionalOutput
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setProportionalOutput
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     dmx_dmxConnect
 * Method:    setProportionalOutputs
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setProportionalOutputs
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    clearProportionalOutput
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_clearProportionalOutput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    clearProportionalOutputs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_clearProportionalOutputs
  (JNIEnv *, jobject, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    setGrandMaster
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setGrandMaster
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     dmx_dmxConnect
 * Method:    setSingle
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setSingle
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     dmx_dmxConnect
 * Method:    setSingleTimed
 * Signature: (IISI)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_setSingleTimed
  (JNIEnv *, jobject, jint, jint, jshort, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    quickLoad
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_quickLoad
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    fullLoadSplit
 * Signature: (I[SII)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_fullLoadSplit
  (JNIEnv *, jobject, jint, jshortArray, jint, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    fullLoad
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_fullLoad
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    partialLoadSplit
 * Signature: (I[S[III)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_partialLoadSplit
  (JNIEnv *, jobject, jint, jshortArray, jintArray, jint, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    partialLoad
 * Signature: (I[S[II)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_partialLoad
  (JNIEnv *, jobject, jint, jshortArray, jintArray, jint);

/*
 * Class:     dmx_dmxConnect
 * Method:    complexLoadSplit
 * Signature: (I[S[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_complexLoadSplit
  (JNIEnv *, jobject, jint, jshortArray, jintArray, jintArray, jintArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    complexLoad
 * Signature: (I[S[I[I)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_complexLoad
  (JNIEnv *, jobject, jint, jshortArray, jintArray, jintArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    getCurrentFade
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_getCurrentFade
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    getCurrentOutput
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_getCurrentOutput
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    getVersion
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_getVersion
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     dmx_dmxConnect
 * Method:    lookUpReturn
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dmx_dmxConnect_lookUpReturn
  (JNIEnv *, jobject, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
